# This is a basic workflow to help you get started with Actions

name: CI gfortran DEBUG

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      ##- name: Install gfortran
      ##  run: |
      ##   sudo add-apt-repository ppa:ubuntu-toolchain-r/test
      ##   sudo apt update
      ##   sudo apt-get install gfortran-9
      
      ##- name: Show gfortran version
      ##  run: gfortran-9 --version
      - name: Show gfortran version
        run: gfortran --version

      - name: Configure
        working-directory: ./Solver
        run: ./configure
      
      - name: Compile horses3d gfortran DEBUG
        working-directory: ./Solver  
        run: |
         make allclean MODE=DEBUG COMPILER=gfortran COMM=SEQUENTIAL ENABLE_THREADS=NO
         make MODE=DEBUG COMPILER=gfortran COMM=SEQUENTIAL ENABLE_THREADS=NO

########################################################################
#######                         COMPONENTS                      ########
########################################################################
#
# 1) FACE PATCHES TEST
# --------------------

      - name: Build FacePatches gfortran DEBUG
        working-directory: ./Solver/test/Components/FacePatches
        run: make MODE=DEBUG COMPILER=gfortran COMM=SEQUENTIAL ENABLE_THREADS=NO
      
      - name: Run FacePatches gfortran DEBUG
        working-directory: ./Solver/test/Components/FacePatches
        run: ./bin/FacePatches

#
# 3) HEXMAPPINGS TEST
# -------------------            
#
# 4) HEXMESH TEST
# ---------------
#
# 5) MESHCONSISTENCY TEST
# -----------------------
#
# 6) NODALSTORAGE TEST
# --------------------

########################################################################
#######                         EULER                           ########
########################################################################
#
# 1) DIFFUSER
# -----------

      - name: Build Diffuser gfortran DEBUG
        working-directory: ./Solver/test/Euler/Diffuser/SETUP
        run: make MODE=DEBUG COMPILER=gfortran COMM=SEQUENTIAL ENABLE_THREADS=NO
    
      - name: list files in Diffuser/Setup
        working-directory: ./Solver/test/Euler/Diffuser/SETUP
        run: ls -la 

      - name: list files in Diffuser
        working-directory: ./Solver/test/Euler/Diffuser
        run: ls -la

      - name: ldd horses3d.ns
        working-directory: ./Solver/test/Euler/Diffuser
        run: ldd horses3d.ns 

      - name: run Diffuser gfortran DEBUG
        working-directory: ./Solver/test/Euler/Diffuser
        run: ./horses3d.ns DiffuserFlow.control

#
# 2) UNIFORM FLOW
# ---------------
#
# 3) BOX AROUND CIRCLE
# --------------------
#
# 4) BOX AROUND CIRCLE PIROZZOLI
# ------------------------------
#
# 5) Inviscid TGV with KEPEC
# --------------------------
#
# 6) Vortex transport 2D with KEPEC
# ---------------------------------
#
# 7) Jacobian-Free Newton-Krylov
# ------------------------------
#
# 8) BOX AROUND CIRCLE WITH ADAPTATION
# ------------------------------------

########################################################################
#######                         NAVIER-STOKES                   ########
########################################################################

#
# 0) Convergence
# ------------------------------
#
# 0) Convergence energy
# --------------------------
#
# 0) Convergence entropy
# ---------------------------------
#
# 1) CYLINDER
# -----------
#
# 2) CYLINDER IP
# --------------
#
# 3) CYLINDER BR2
# ---------------
#
# 4) CYLINDER DUCROS
# ------------------
#
# 5) CYLINDER LES
# ------------------
#
# 6) TAYLOR GREEN VORTEX
# ----------------------
#
# 7) TAYLOR GREEN VORTEX KEP BR2
# -----------------------------
#
# 8) TAYLOR GREEN VORTEX KEPEC IP
# -------------------------------
#
# 9) CYLINDER FAS
# ---------------
#
# 10) CYLINDER IP+BDF2
# -------------------
      ##- name: Build NSCylinderIP_BDF2 gfortran DEBUG
      ##  working-directory: ./Solver/test/NavierStokes/CylinderIP_BDF2/SETUP
      ##  run: make MODE=DEBUG COMPILER=gfortran COMM=SEQUENTIAL ENABLE_THREADS=NO
    
      ##- name: Run NSCylinderIP_BDF2 gfortran DEBUG
      ##  working-directory: ./Solver/test/NavierStokes/CylinderIP_BDF2
      ##  run: ./horses3d.ns CylinderIP_BDF2.control
#
# 11) CYLINDER DIFFERENT ORDERS
# ----------------------------
#
# 12) ENTROPY CONSERVING TEST
# ----------------------------
#
# 13) ENERGY CONSERVING TEST
# ----------------------------
########################################################################
#######                       PARTICLES                         ########
########################################################################

#
# 1) FreeFall
# ----------------------------
#
# 2) RadiationHeat
# ----------------------------
#
# 3) ParticleBoundaryCond
# ----------------------------
#
# 4) Pouransari
# ----------------------------
